name: Deploy TouchCanvas to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4          # v3 → v4
      - name: Setup Node.js
        uses: actions/setup-node@v4        # v3 → v4
        with:
          node-version: '20'               # 18 → 20
      - name: Install dependencies
        run: npm install
      - name: Build TouchCanvas
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # v3 → v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
